ALTER PROCEDURE SMART_UPINSERT AS
BEGIN -- BEGIN INICIO
BEGIN TRY -- INICIO TRY
DECLARE @FILAS_SMART_TMP AS INTEGER
DECLARE @FILAS_SMART_REMOTO AS INTEGER
 SET @FILAS_SMART_TMP=(SELECT COUNT(*) FROM SMART_TMP WITH (NOLOCK))
 -- SI HAY REGISTROS EN SMART_TMP INGRESA
 IF(@FILAS_SMART_TMP>0)
 BEGIN  -- INICIO SI HAY REGISTROS EN SMART_TMP INGRESA
 DECLARE SMART_CURSOR CURSOR FOR SELECT SEQ_ID FROM SMART_TMP WITH (NOLOCK) ORDER BY SEQ_ID DESC -- MUY IMPORTANTE DE DESC
																								-- PARA QUE LEA LO MAS NUEVO
																								 --Y BORRE LO VIEJO
 DECLARE @SEQ_ID AS INTEGER
 DECLARE @DES_DYNDNS AS VARCHAR(200)
 DECLARE @NUM_PORT AS INTEGER
 DECLARE @DES_USER AS VARCHAR(200)
 DECLARE @DES_PASSWORD AS VARCHAR(200)
 DECLARE @DES_COUNTRY_ID AS VARCHAR(20)
 DECLARE @COD_CONNECTION_ID AS VARCHAR(200)
 DECLARE @DES_CONTRACT_NUMBER AS VARCHAR(200)
 DECLARE @DES_PROVIDER AS VARCHAR(4)
 DECLARE @MAX_SEQ_ID_MAS_UNO AS INTEGER
 DECLARE @REGISTROS AS INTEGER
 
 
 -- 
	OPEN SMART_CURSOR
 
 --FETCH NEXT FROM SMART_CURSOR INTO @SEQ_ID

	WHILE @@fetch_status = 0

	BEGIN -- INICIO WHILE

    FETCH NEXT FROM SMART_CURSOR INTO @SEQ_ID -- ID DE LA TABLA SMART_TMP
    SELECT 
    @DES_DYNDNS=DES_DYNDNS,
    @NUM_PORT=NUM_PORT,
    @DES_USER=DES_USER,
    @DES_PASSWORD=DES_PASSWORD,
    @DES_COUNTRY_ID=DES_COUNTRY_ID,
    @COD_CONNECTION_ID=COD_CONNECTION_ID,
    @DES_CONTRACT_NUMBER=DES_CONTRACT_NUMBER,
    @DES_PROVIDER=DES_PROVIDER 
    FROM Smart_Tmp WITH (NOLOCK) WHERE SEQ_ID=@SEQ_ID
    
   /**/
   -- VER SI EN LA TABLA REMOTA DE SMART EXISTEN REGISTROS CON CONTRATOS X
   SET @FILAS_SMART_REMOTO=(SELECT COUNT(*) FROM [SMART]..[ACTIVEMB].[SMPR_TVIDEO_CREDENTIALS] WITH (NOLOCK) WHERE DES_CONTRACT_NUMBER=@DES_CONTRACT_NUMBER)
   SET @REGISTROS=@FILAS_SMART_REMOTO
   IF (@REGISTROS=0) -- SI NO HAY REGISTROS EN LA TABLA SMPR_TVIDEO_CREDENTIALS CON ÉSE CONTRATO , INSERTO
   BEGIN -- INICIO -- SI NO HAY REGISTROS EN LA TABLA SMPR_TVIDEO_CREDENTIALS CON ÉSE CONTRATO , INSERTO
   /**/
   --************************************************************************************************************
   -- GENERAMOS EL NÚMERO DE SECUENCIA PARA LA TABLA SMPR_TVIDEO_CREDENTIALS
   SET @MAX_SEQ_ID_MAS_UNO=(SELECT MAX(SEQ_ID) FROM [SMART]..[ACTIVEMB].[SMPR_TVIDEO_CREDENTIALS] WITH (NOLOCK))
		IF (@MAX_SEQ_ID_MAS_UNO IS NULL)
		BEGIN -- INICIO, INICIALIZAR SECUENCIA NULL
		SET @MAX_SEQ_ID_MAS_UNO=1
		END -- FIN -- INICIO, INICIALIZAR SECUENCIA NULL
		ELSE -- INICIO, INICIALIZAR SECUENCIA SIGUIENTE
		BEGIN 
		SET @MAX_SEQ_ID_MAS_UNO=@MAX_SEQ_ID_MAS_UNO+1
		END -- INICIO, INICIALIZAR SECUENCIA SIGUIENTE
	 -- FIN GENERAMOS EL NÚMERO DE SECUENCIA PARA LA TABLA SMPR_TVIDEO_CREDENTIALS	
	 --***********************************************************************************************************
	 
	 IF( -- SI QUIERE INSERTAR TODOS LOS CAMPOS IMPORTANTES EN NULL
		@DES_DYNDNS is null and
		@NUM_PORT is null and
		@DES_USER is null and
		@DES_PASSWORD is null and
		@DES_PROVIDER is null)
		
		BEGIN -- INICIO BORRAR AMBAS TABLAS EN FUNCION DE CONTRATO
		-- BORRAMOS DE LAS DOS TABLAS
		DELETE FROM [SMART]..[ACTIVEMB].[SMPR_TVIDEO_CREDENTIALS] WHERE DES_CONTRACT_NUMBER=@DES_CONTRACT_NUMBER
		DELETE FROM Smart_Tmp WHERE DES_CONTRACT_NUMBER=@DES_CONTRACT_NUMBER
		
		END ---- INICIO BORRAR AMBAS TABLAS EN FUNCION DE CONTRATO
		ELSE --- SINO SI HAY AL MENOS UN CAMPO IMPORTANTE NO NULL INSERTA 
		BEGIN 
		INSERT INTO [SMART]..[ACTIVEMB].[SMPR_TVIDEO_CREDENTIALS](
		SEQ_ID,
		DES_DYNDNS,
		NUM_PORT,
		DES_USER,
		DES_PASSWORD,
		DES_COUNTRY_ID,
		COD_CONNECTION_ID,
		DES_CONTRACT_NUMBER,
		DES_PROVIDER
		)VALUES(
		@MAX_SEQ_ID_MAS_UNO,
		@DES_DYNDNS,
		@NUM_PORT,
		@DES_USER,
		@DES_PASSWORD,
		@DES_COUNTRY_ID,
		@COD_CONNECTION_ID,
		@DES_CONTRACT_NUMBER,
		@DES_PROVIDER
		)
		
		END -- FIN SINO, SI HAY AL MENOS UN CAMPO IMPORTANTE NO NULL INSERTA 
  
		END -- FIN SI NO HAY REGISTROS EN LA TABLA SMPR_TVIDEO_CREDENTIALS CON ÉSE CONTRATO , INSERTO
		ELSE IF(@REGISTROS>0) 
		BEGIN   -- INICIO -- SI HAY REGISTROS EN LA TABLA SMPR_TVIDEO_CREDENTIALS, ACTUALIZO O BORRO DE SMART SI ES QUE LOS 5 CAMPOS SON NULL.
  
		-- SI LOS CAMPOS IMPORTANTES A INSERTAR, ESTÁN VACÍOS, BORRAR DE SMPR_TVIDEO_CREDENTIALS Y BORRAR DE SMART_TMP
		IF(
		@DES_DYNDNS is null and
		@NUM_PORT is null and
		@DES_USER is null and
		@DES_PASSWORD is null and
		@DES_PROVIDER is null)
		
		BEGIN -- INICIO BORRAR DE SMPR_TVIDEO_CREDENTIALS Y BORRAR DE SMART_TMP
		DELETE FROM SMART_TMP WHERE DES_CONTRACT_NUMBER=@DES_CONTRACT_NUMBER
		DELETE FROM [SMART]..[ACTIVEMB].[SMPR_TVIDEO_CREDENTIALS] WHERE DES_CONTRACT_NUMBER=@DES_CONTRACT_NUMBER	
		END  --BORRAR DE SMPR_TVIDEO_CREDENTIALS Y BORRAR DE SMART_TMP
		ELSE 
		BEGIN -- SI LOS CAMPOS NO ESTÁN VACÍOS. AL MENOS UNO DE LOS IMPORTANTES, INSERTO EN LA TABLA SMPR_TVIDEO_CREDENTIALS
	
		update [SMART]..[ACTIVEMB].[SMPR_TVIDEO_CREDENTIALS]
		set 
		DES_DYNDNS =@DES_DYNDNS,
		NUM_PORT = @NUM_PORT,
		DES_USER =@DES_USER,
		DES_PASSWORD =@DES_PASSWORD,
		DES_COUNTRY_ID =@DES_COUNTRY_ID,
		COD_CONNECTION_ID=@COD_CONNECTION_ID,
		DES_CONTRACT_NUMBER=@DES_CONTRACT_NUMBER,
		DES_PROVIDER =@DES_PROVIDER
		WHERE DES_CONTRACT_NUMBER=@DES_CONTRACT_NUMBER
		
		
		DELETE FROM SMART_TMP WHERE DES_CONTRACT_NUMBER=@DES_CONTRACT_NUMBER
		
		END -- FIN SI LOS CAMPOS NO ESTÁN VACÍOS. AL MENOS UNO DE LOS IMPORTANTES, INSERTO EN LA TABLA SMPR_TVIDEO_CREDENTIALS
		
			
		
		END 


		CLOSE SMART_CURSOR

		DEALLOCATE SMART_CURSOR
		END
		END


		-- SI LA TABLA ESTÁ VACÍA EN LOCAL, REINICIÁMOS CONTADOR AUTOINCREMENT.
		IF((SELECT COUNT(*) FROM Smart_Tmp)=0)BEGIN DBCC CHECKIDENT (Smart_Tmp, RESEED,0) END

		END TRY -- FIN INICIO TRY
		BEGIN CATCH -- INICIO CATCH
		SELECT 'DEFINIR ERROR Y DÓNDE GUARDARLO'
		UPDATE SMART_TMP SET 
		ERROR=ERROR_MESSAGE(),
		ERROR_FECHA=GETDATE()
		
		WHERE DES_CONTRACT_NUMBER=@DES_CONTRACT_NUMBER;
		END CATCH -- FIN INICIO CATCH

		END --FIN -- BEGIN INICIO