USE MonitorTestDB
DROP TRIGGER trg_site_option_smart
GO
CREATE TRIGGER trg_site_option_smart
   ON  site_option
   FOR INSERT,UPDATE,DELETE
   
AS 
BEGIN

DECLARE @MASVIDIP AS VARCHAR(100)
DECLARE @MASVIDPORT AS VARCHAR(100)
DECLARE @MASVIDUSER AS VARCHAR(100)
DECLARE @MASVIDPASS AS VARCHAR(100)
DECLARE @MASVIDTYPE AS VARCHAR(100)
DECLARE @MASVIDCOUNTRY AS VARCHAR(100)
DECLARE @MASVIDCSNO AS VARCHAR(100)
DECLARE @MASVIDUDF4 AS VARCHAR(100)
DECLARE @FILAS AS INTEGER
DECLARE @SECUENCIA AS INTEGER
DECLARE @SITE_NO AS INTEGER
DECLARE @SITE_NO_TEMP_DELETED AS INTEGER 
DECLARE @SITE_NO_TEMP_INSERTED AS INTEGER
--*************************************************
IF EXISTS (SELECT SITE_NO FROM DELETED WITH (NOLOCK))
	BEGIN
	SET @SITE_NO_TEMP_DELETED=(SELECT SITE_NO FROM DELETED WITH (NOLOCK))
	END
IF EXISTS (SELECT SITE_NO FROM INSERTED WITH (NOLOCK))
	BEGIN
	SET @SITE_NO_TEMP_INSERTED=(SELECT SITE_NO FROM INSERTED WITH (NOLOCK))
	END

IF (@SITE_NO_TEMP_DELETED IS NOT NULL)
	BEGIN
	SET @SITE_NO=@SITE_NO_TEMP_DELETED
	END
IF (@SITE_NO_TEMP_INSERTED IS NOT NULL)
	BEGIN
	SET @SITE_NO=@SITE_NO_TEMP_INSERTED
	END

IF(@SITE_NO IS NOT NULL) 
	BEGIN
--*******************************************************
	SET @MASVIDUDF4=(SELECT UDF4 FROM SITE S WITH (NOLOCK) WHERE S.SITE_NO=@SITE_NO)--DES_CONTRACT_NUMBER

--********************************************************
	SET @MASVIDIP=(SELECT OPTION_VALUE FROM SITE_OPTION WITH (NOLOCK) WHERE OPTION_ID=  'MAS_VIDEO_IP' AND SITE_NO=@SITE_NO)
	SET @MASVIDPORT=(SELECT OPTION_VALUE FROM SITE_OPTION WITH (NOLOCK) WHERE OPTION_ID='MAS_VIDEO_PORT' AND SITE_NO=@SITE_NO)
	SET @MASVIDUSER=(SELECT OPTION_VALUE FROM SITE_OPTION WITH (NOLOCK) WHERE OPTION_ID='MAS_VIDEO_USERNAME' AND SITE_NO=@SITE_NO)
	SET @MASVIDPASS=(SELECT OPTION_VALUE FROM SITE_OPTION WITH (NOLOCK) WHERE OPTION_ID='MAS_VIDEO_PASSWORD' AND SITE_NO=@SITE_NO)
	SET @MASVIDPASS=DBO.ENCRIPTARFIB(@MASVIDPASS)
	SET @MASVIDTYPE=(SELECT OPTION_VALUE FROM SITE_OPTION WITH (NOLOCK) WHERE OPTION_ID='MAS_VIDEO_TYPE' AND SITE_NO=@SITE_NO) 
	SET @MASVIDCOUNTRY=(SELECT CASE (COUNTRY_NAME) 
-- CODIGOS PROPORCIONADOS POR FACUNDO SUAREZ CHAGRA
	WHEN 'Argentina' THEN 'ES'
	WHEN 'Brasil' THEN 'BR'
	WHEN 'Chile' THEN 'CL'
	WHEN 'Colombia' THEN 'CO'
	WHEN 'España' THEN 'ES'
	WHEN 'Great Britain' THEN 'GB'
	WHEN 'Peru' THEN 'PE'
	WHEN 'Portugal' THEN 'PT'
	WHEN 'Paraguay' THEN 'PY'
	WHEN 'Uruguay' THEN 'UY'
	ELSE '**'
	END
	
	FROM SITE WITH (NOLOCK) WHERE SITE_NO=@SITE_NO)--DES_COUNTRY_ID
	
	SET @MASVIDCSNO=(SELECT MAX(CS_NO) FROM SYSTEM S WITH (NOLOCK) WHERE SITE_NO=@SITE_NO)--COD_CONNECTION_ID-> PUEDE HABER MÁS DE UN CS_NO POR SITE


	--INSERTAMOS LOS VALORES ACTUALES DE MASTERMIND EN UNA TABLA TEMPORAL (SMART_TMP)

		INSERT INTO SMART_TMP(
		DES_DYNDNS,
		NUM_PORT,
		DES_USER,
		DES_PASSWORD,
		DES_COUNTRY_ID,
		COD_CONNECTION_ID,
		DES_CONTRACT_NUMBER,
		DES_PROVIDER
		)VALUES(
		
		@MASVIDIP,
		@MASVIDPORT,
		@MASVIDUSER,
		@MASVIDPASS,
		@MASVIDCOUNTRY,
		@MASVIDCSNO,
		@MASVIDUDF4,
		@MASVIDTYPE)

   END

END
